name: Build project

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Deploy Store Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 177b60ae-4ee5-4cf3-92e7-556aecf0460a
          heroku_app_name: lab2-store-service
          heroku_email: yuhan.dong@yandex.ru
          appdir: store-service

      - name: Deploy Warranty Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 177b60ae-4ee5-4cf3-92e7-556aecf0460a
          heroku_app_name: lab2-warranty-service
          heroku_email: yuhan.dong@yandex.ru
          appdir: warranty-service

      - name: Deploy Warehouse Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 177b60ae-4ee5-4cf3-92e7-556aecf0460a
          heroku_app_name: lab2-warehouse-service
          heroku_email: yuhan.dong@yandex.ru
          appdir: warehouse-service

      - name: Deploy Order Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: 177b60ae-4ee5-4cf3-92e7-556aecf0460a
          heroku_app_name: lab2-order-service
          heroku_email: yuhan.dong@yandex.ru
          appdir: order-service

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
